---
title: "CV Frederik Prip"
---

<a href="CV.pdf#" class="download" title="Download CV as PDF">Download CV</a>			

**Current position**
MD, PhD student \
Bladder group   \
Department of Molecular Medicine (MOMA) \
Aarhus University Hospital \

**Languages **
Danish, mother tongue \
English, talk and write fluently \  

**Educational background** 				 
2016 - Present
Arhus University, Master’s degree in medicine (completed 11. Semester) 
2013-2016
Aarhus University, Bachelor’s degree in medicine 	
Grade average 8.57 	
2008 – 2011
STX, Ordrup Gymnasium 
	 
**Research involvement: **					
01/09-2017 - 31/08-2018
Research year, Immune cell characterization of molecular subtypes in early stage bladder cancer
The department of Molecular Medicine, Aarhus University

01/06-2017- 31/07-2017	
Research assistant 				
The Department of Clinical Biochemistry, Aalborg University Hospital,
Practicing different techniques to isolate platelet microvesicles from plasma 
01/07-2015 -31/07-2015
Research exchange 			        
The department of Genomic science and biotechnology, Universidade Católica de Brasília, Brazil
Characterisation of exosomes and its content in the blood before, during and after exercise. 

**Publications**
STAG2 Is a Biomarker for Prediction of Recurrence and Progression in Papillary Non-Muscle-Invasive Bladder Cancer.
Lelo A, Prip Frederik, Harris BT, Solomon D, Berry DL, Chaldekas K, Kumar A, Simko J, Jensen JB, Bhattacharyya P, Mannion C, Kim JS, Philips G, Dyrskjøt L, Waldman T.
Clin Cancer Res. 2018 Jun 28. doi: 10.1158/1078-0432.CCR-17-3244
Disseminations:
Oral presentation at the International Bladder Cancer Network (IBCN) meeting 2019  
Oral presentation at the annual congress for medical research students 2019
Poster presentation at PhD day 2018				
Poster presentation at the annual congress for medical research students 2018					
Other skills and qualifications 
01/08-2016-03/01/2019						
Deputy chairman of the Oncological Association for Medical Students, Aarhus – OSM	

Grants: 
2019: Part A PhD Scholarships, Graduate School of HEALTH, Aarhus University
2019: Research training supplement, Graduate School of HEALTH, Aarhus University: 550.000 DKK 
2017: Grosserer Georg Bjørkner og Hustru Ellen Bjørkners Fond: 10.000 kr.
2017: Grosserer L.F. Foghts Fond: 65.000 kr.
2017: The Danish Cancer Society: 120.000 kr. 
